export const USER_ROLES = {
  ADMIN: "ADMIN",
  INSTRUCTOR: "INSTRUCTOR",
  STUDENT: "STUDENT",
};

export const GET_TOOLS_TYPES = {
  CURRENT: "CURRENT",
  ALL: "ALL",
};

export const BORROW_STATUSES = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  RETURNED: "RETURNED",
};

export const BORROW_INSTRUCTOR_ALLOWED_STATUSES = [
  BORROW_STATUSES.REQUESTED,
  BORROW_STATUSES.APPROVED,
  BORROW_STATUSES.REJECTED
];
